export const authorisedData = [
    {
        id: 1,
       name: 'Wonka Industries',
       Pan: 'ABCDE1234F',
       Email: 'johndoe@gmail.com',
       connection: 'Vendor',
       sent: 'John Doe',
    },
    {
        id: 2,
       name: 'Deepesh Khatri and Associates',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Vendor',
       sent: 'Jenny Wilson',
    },
    {
        id: 3,
       name: 'Mentor',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Customer',
       sent: 'Kristin Watson',
    },
    {
        id: 4,
       name: 'The Career Coach',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Vendor',
       sent: 'Floyd Miles',
    },
    {
        id: 5,
       name: 'Roll It Up',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: ['Vendor', 'Customer'],
       sent: 'Darlene Robertson',
    },
    {
        id: 6,
       name: 'Shimmering Beauty',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: ['Vendor', 'Customer'],
       sent: 'Robert Fox',
    },
    {
        id: 7,
       name: 'Squeaky Clean',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Customer',
       sent: 'Brooklyn Simmons',
    },
    {
        id: 8,
       name: 'Phoenix',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Customer',
       sent: 'Eleanor Pena',
    },
    {
        id: 9,
       name: 'Operify',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Customer',
       sent: 'Albert Flores',
    },
    {
        id: 10,
       name: 'Squeaky Clean',
       Pan: 'ABCDE1234F',
       Email: 'samplename@gmail.com',
       connection: 'Customer',
       sent: 'Brooklyn Simmons',
    },
]